### ISSUE TITLE
eaf-markmap在emacs frame较宽时，打开文件会创建多个重复的窗口

### ISSUE THREAD

**Issue by nowislewis** [emacs-eaf/eaf-markmap#3]
额外说明：经测试，该问题仅在emacs frame size比较宽的时候(3840 pixel)时出现，而frame较小时没有该现象
测试环境:
1. wslg+archlinux
2. eaf-markmap版本:[25340e8](https://github.com/emacs-eaf/eaf-markmap/commit/25340e8e9a6a0fe45e42854a33a2c3ed89be5369)
3. 测试配置：使用emacs -Q 测试，配置如下：
``` elisp
(add-to-list 'load-path "~/.emacs.d/lib/eaf/")
(require 'eaf)
(require 'eaf-markmap)
```
测试流程如下：
1. 创建一个test.org文件
2. 使用eaf-open打开这个test.org文件
    - 现象：emacs会先左右分两屏，分别是test.org和对应markmap的窗口，短暂延时后，自动创建多个test.org窗口
3. 使用delete-other-window命令
    - 现象：仅保留一个test.org窗口，一小段延时后，自动出现了四个横向分布的test.org窗口
![动画](https://github.com/emacs-eaf/eaf-markmap/assets/41566630/30172de5-ee9a-46c6-a733-9be73f1902ed)

**Comment by manateelazycat** [comment]
你的分辨率有多少？

**Comment by nowislewis** [comment]
我刚测试了两个屏幕，分别为宽屏的3440x1440和常规比例的3840x2160，都会出现该现象。不清楚是不是和wslg有关，现在手边没有纯粹的linux环境

**Comment by manateelazycat** [comment]
建议在 elisp 和 python 都加入很多 print 或者 message 语句， 看看定位到哪行代码出错了？

只要能定位问题， 应该都可以修复。

我才换了电脑， 从 4k 换成了 2k, 目前还没法测试你说的这种问题。
